CREATE DATABASE APRESENTACAO;

USE APRESENTACAO;

CREATE TABLE CADASTRO (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL
	,SITUACAO VARCHAR (255) NOT NULL
);

CREATE TABLE INFORMACAO (
	QUANT_PESSOAS INT NOT NULL
	,QUANT_CONFIRMADO VARCHAR (255) NOT NULL
	,QUANT_CANCELADO VARCHAR (255) NOT NULL
	,QUANT_AGUARDANDO VARCHAR (255) NOT NULL
);

-----Visualização-----

SELECT * FROM CADASTRO
SELECT * FROM INFORMACAO

-----Deletes-----
DELETE INFORMACAO
DROP TABLE CADASTRO
DROP TABLE INFORMACAO
DROP TRIGGER ATUALIZAR_INFORMACAO

-----Trigger-----
CREATE TRIGGER ATUALIZAR_INFORMACAO
		ON CADASTRO
	AFTER INSERT
		AS
	UPDATE INFORMACAO
	SET QUANT_PESSOAS = (
     SELECT COUNT(NOME)
     FROM CADASTRO),
	 QUANT_CONFIRMADO = (
     SELECT COUNT(NOME)
     FROM CADASTRO WHERE SITUACAO = 'Sim'),
	 QUANT_AGUARDANDO = (
     SELECT COUNT(NOME)
     FROM CADASTRO WHERE SITUACAO = 'Talvez'),
	 QUANT_CANCELADO = (
     SELECT COUNT(NOME)
     FROM CADASTRO WHERE SITUACAO = 'Não');

-----Inserir valores------

INSERT INTO INFORMACAO VALUES (0,0,0,0) -- Essa linha é por causa do 'update' no trigger

INSERT INTO CADASTRO (NOME, SITUACAO)
VALUES		('Pessoa 1','Sim')
			,('Pessoa 2','Não')
			,('Pessoa 3','Sim')
			,('Pessoa 4','Não')
			,('Pessoa 5','Talvez')
			,('Pessoa 6','Talvez')
			,('Pessoa 7','Talvez')