CREATE DATABASE SSOLVE

USE SSOLVE;

CREATE TABLE EMPRESAS (
	ID INT IDENTITY PRIMARY KEY
	,NOME_FANTASIA VARCHAR (255) NOT NULL UNIQUE
	,CNPJ CHAR (14)
	,RAZAO_SOCIAL VARCHAR (255) NOT NULL
	,ENDERECO VARCHAR (255) NOT NULL
); 

CREATE TABLE AREA_SERVICO (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE FUNCIONARIOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL
);

CREATE TABLE ITENS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE TIPOS_SERVICOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE SERVICOS (
	ID INT IDENTITY PRIMARY KEY
	,ID_AREA_SERVICO INT FOREIGN KEY REFERENCES AREA_SERVICO(ID)
	,ID_EMPRESA INT FOREIGN KEY REFERENCES EMPRESAS (ID)
	,ID_ITEM INT FOREIGN KEY REFERENCES ITENS (ID)
	,ID_TIPO_SERVICO INT FOREIGN KEY REFERENCES TIPOS_SERVICOS (ID)
	,DATA_INICIO DATETIME
	,DATA_TERMINO DATETIME
	,PRECO DECIMAL (18,2)
);

CREATE TABLE FUNCIONARIOS_E_SERVICOS (
	ID INT IDENTITY PRIMARY KEY
	,ID_SERVICO INT FOREIGN KEY REFERENCES SERVICOS (ID)
	,ID_FUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIOS (ID)
);

ALTER TABLE FUNCIONARIOS_E_SERVICOS
DROP COLUMN ID