CREATE DATABASE SENAI_HCURSOS_TARDE;

USE SENAI_HCURSOS_TARDE;

CREATE TABLE CATEGORIAS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (250) NOT NULL UNIQUE
);

CREATE TABLE PROFESSORES (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (250) NOT NULL
);

CREATE TABLE ALUNOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (250) NOT NULL
);

CREATE TABLE CURSOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (250) NOT NULL
	,TITULO VARCHAR (250) NOT NULL
	,ID_PROFESSOR INT NOT NULL FOREIGN KEY REFERENCES PROFESSORES(ID)
	,ID_CATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(ID)
);

CREATE TABLE CURSOS_ALUNOS (
	ID_CURSO INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID)
	,ID_ALUNO INT NOT NULL FOREIGN KEY REFERENCES ALUNOS(ID)
);
