INSERT INTO EVENTOS (TITULO, DESCRICAO, DATA_EVENTO, ACESSO_LIVRE, ID_INSTITUICAO, ID_TIPO_EVENTO)
VALUES (('Perfil Vencedor'),('Aprenda técnicas para o Linkedin'),('2019-04-05'),1,4,3)

SELECT EVENTOS.ID AS ID_EVENTO,
	   EVENTOS.TITULO AS TITULO_EVENTO ,
	   EVENTOS.DESCRICAO,
	   EVENTOS.DATA_EVENTO,
	   EVENTOS.ACESSO_LIVRE,
	   TIPOS_EVENTOS.ID AS ID_TIPO_EVENTO,
	   TIPOS_EVENTOS.TITULO AS TITULO_TIPO_EVENTO,
	   INSTITUICOES.ID AS ID_INSTITUICAO,
	   INSTITUICOES.NOME_FANTASIA,
	   INSTITUICOES.RAZAO_SOCIAL,
	   INSTITUICOES.CNPJ,
	   INSTITUICOES.LOGRADOURO,
	   INSTITUICOES.CEP,
	   INSTITUICOES.UF,
	   INSTITUICOES.CIDADE

FROM EVENTOS INNER JOIN TIPOS_EVENTOS
ON 
EVENTOS.ID_TIPO_EVENTO = TIPOS_EVENTOS.ID
INNER JOIN
INSTITUICOES
ON
EVENTOS.ID_INSTITUICAO = INSTITUICOES.ID

select * from EVENTOS