CREATE DATABASE InLock_Games_Tarde;

USE InLock_Games_Tarde;

CREATE TABLE Estudios (
	EstudioId INT IDENTITY PRIMARY KEY
	,NomeEstudio VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE Jogos (
	JogoId INT IDENTITY PRIMARY KEY
	,NomeJogo VARCHAR (255) NOT NULL UNIQUE
	,Descricao TEXT NOT NULL
	,DataLancamento DATE NOT NULL
	,Valor DECIMAL NOT NULL -- ou MONEY
	,EstudioId INT FOREIGN KEY REFERENCES Estudios(EstudioId)
);

CREATE TABLE Usuarios (
	UsuarioId INT IDENTITY PRIMARY KEY
	,Email VARCHAR (250) NOT NULL UNIQUE
	,Senha VARCHAR (255) NOT NULL
	,TipoUsuario VARCHAR (255) NOT NULL
);